NAMESPACE := "tms-jr-d"
KN := "kubectl -n tms-jr-d"

get-pods-with-gpus:
 kubectl get pods --all-namespaces \
  -o jsonpath='{range .items[?(@.spec.containers[*].resources.requests.nvidia\.com/gpu)]}{.metadata.namespace}{"\t"}{.metadata.name}{"\n"}{end}'

start:
  helmfile --selector managedBy=helmfile apply helmfile.yaml
stop:
  helmfile --selector managedBy=helmfile apply helmfile.yaml
restart:
  just stop && just start

hf_secret:
  kubectl create secret generic hf-secret \
  --from-literal=HF_TOKEN=${HF_TOKEN} \
  --dry-run=client -o yaml | kubectl apply -f -

start-bench:
  kubectl apply -f benchmark-interactive-pod.yaml

exec-bench:
    kubectl cp Justfile.remote {{NAMESPACE}}/benchmark-interactive:/app/Justfile \
    && {{KN}} exec -it benchmark-interactive -- /bin/bash
